services:
    web:
        build: .
        container_name: LaraSlim_app
        ports:
            - "8003:80"
        volumes:
            - ./:/var/www/html
    mysql:
        image: mysql:latest
        container_name: LaraSlim_mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - laraSlim-mysql:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: LaraSlim_phpmyadmin
        restart: always
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
volumes:
    laraSlim-mysql:
        driver: local
