name: "Skeleton Project PHP"
services:
  web:
    build: .
    container_name: skeleton_php
    ports:
      - "8003:80"
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:latest
    container_name: skeleton_mysql
    restart: always
    environment:
      MYSQL_DATABASE: skeleton_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: skeleton_phpmyadmin
      restart: always
      depends_on:
        - mysql
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "8080:80"